export const SUBHEADER_LIST_REQUEST = "SUBHEADER_LIST_REQUEST";
export const SUBHEADER_LIST_SUCCESS = "SUBHEADER_LIST_SUCCESS";
export const SUBHEADER_LIST_FAIL = "SUBHEADER_LIST_FAIL";

export const SUBHEADER_DETAILS_REQUEST = "SUBHEADER_DETAILS_REQUEST";
export const SUBHEADER_DETAILS_SUCCESS = "SUBHEADER_DETAILS_SUCCESS";
export const SUBHEADER_DETAILS_FAIL = "SUBHEADER_DETAILS_FAIL";
export const SUBHEADER_DETAILS_RESET = "SUBHEADER_DETAILS_RESET";


export const SUBHEADER_DELETE_REQUEST = "SUBHEADER_DELETE_REQUEST";
export const SUBHEADER_DELETE_SUCCESS = "SUBHEADER_DELETE_SUCCESS";
export const SUBHEADER_DELETE_FAIL = "SUBHEADER_DELETE_FAIL";

export const SUBHEADER_CREATE_REQUEST = "SUBHEADER_CREATE_REQUEST";
export const SUBHEADER_CREATE_SUCCESS = "SUBHEADER_CREATE_SUCCESS";
export const SUBHEADER_CREATE_FAIL = "SUBHEADER_CREATE_FAIL";
export const SUBHEADER_CREATE_RESET = "SUBHEADER_CREATE_RESET";

export const SUBHEADER_UPDATE_REQUEST = "SUBHEADER_UPDATE_REQUEST";
export const SUBHEADER_UPDATE_SUCCESS = "SUBHEADER_UPDATE_SUCCESS";
export const SUBHEADER_UPDATE_FAIL = "SUBHEADER_UPDATE_FAIL";
export const SUBHEADER_UPDATE_RESET = "SUBHEADER_UPDATE_RESET";
